### ISSUE TITLE
Document-Service: Fehler beim Einlesen der Permissions

### ISSUE THREAD

**Issue by ojeker** [simi-so/json2qgs#31]
Hoi Mathias

Da scheint etwas mit dem permission.json nicht zu passen...?
Es macht keinen Unterschied, ob der Report als "afu_geotope.pdf" oder "afu_geotope" bezeichnet ist. In beiden Fällen permission error.

Stacktrace folgt, *.json liegen bei.

    [pid: 8|app: 0|req: 381/381] 172.22.2.1 () {26 vars in 309 bytes} [Thu Aug 12 09:18:48 2021] GET /healthz => generated 21 bytes in 0 msecs (HTTP/1.1 200) 5 headers in 135 bytes (1 switches on core 0)
    [2021-08-12 09:18:51,013] INFO in runtime_config: Reading runtime config '/srv/qwc_service/config/default/documentConfig.json'
    [2021-08-12 09:18:51,015] INFO in permissions_reader: Reading permissions '/srv/qwc_service/config/default/permissions.json'
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
        response = self.handle_exception(e)
      File "/usr/lib/python3.6/site-packages/flask_restx/api.py", line 638, in error_router
        return original_handler(f)
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
        raise value
      File "/usr/lib/python3.6/site-packages/flask_restx/api.py", line 636, in error_router
        return self.handle_error(e)
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/lib/python3.6/site-packages/flask_restx/api.py", line 638, in error_router
        return original_handler(f)
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
        raise value
      File "/usr/lib/python3.6/site-packages/flask_restx/api.py", line 636, in error_router
        return self.handle_error(e)
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/lib/python3.6/site-packages/flask_restx/api.py", line 375, in wrapper
        resp = resource(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/flask/views.py", line 89, in view
        return self.dispatch_request(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/flask_restx/resource.py", line 44, in dispatch_request
        resp = meth(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 129, in wrapper
        return fn(*args, **kwargs)
      File "./server.py", line 103, in get
        return get_document(tenant, template, format)
      File "./server.py", line 49, in get_document
        permissions_handler = PermissionsReader(tenant, app.logger)
      File "/usr/lib/python3.6/site-packages/qwc_services_core/permissions_reader.py", line 32, in __init__
        self.permissions = self.load_permissions()
      File "/usr/lib/python3.6/site-packages/qwc_services_core/permissions_reader.py", line 83, in load_permissions
        for role in user['roles']:
    TypeError: 'NoneType' object is not iterable
    [pid: 8|app: 0|req: 382/382] 172.20.4.1 () {76 vars in 2259 bytes} [Thu Aug 12 09:18:51 2021] GET /api/v1/document/afu_geotope.pdf?feature=8465&x=2631942.5820000838&y=1247014.2630599793&crs=EPSG%3A2056 => generated 0 bytes in 20 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 1)
    [pid: 8|app: 0|req: 383/383] 172.22.2.1 () {26 vars in 305 bytes} [Thu Aug 12 09:19:17 2021] GET /ready => generated 21 bytes in 1 msecs (HTTP/1.1 200) 5 headers in 135 bytes (1 switches on core 2)

[documentConfig.json.txt](https://github.com/simi-so/json2qgs/files/6974139/documentConfig.json.txt)
[permissions.json.txt](https://github.com/simi-so/json2qgs/files/6974140/permissions.json.txt)

**Comment by mwa** [comment]
Die Docker Images für den Document Service wurden seit `v2.0.0` nicht mehr richtig publiziert, so dass in `latest` noch nicht die neuen Permissions unterstützt wurden.

Mit `qwc-document-service:v2.0.3` sollte es jetzt funktionieren.
